export type Lesson = {
  id: string;
  title: string;
  name: string;
  category: 'Scales' | 'Songs' | 'Exercises';
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  lessonCount: number;
  description: string;
  learns: string[];
  previewDuration: string;
  emoji: string;
  bgColor: string;
};

export const LESSONS: Lesson[] = [
  // ─── SCALES ────────────────────────────────────────────────────────────────
  {
    id: 'scale-01',
    title: 'Basic Scale Sa Re Ga Ma',
    name: 'Foundation Sargam',
    category: 'Scales',
    difficulty: 'Beginner',
    lessonCount: 4,
    description:
      'Start your flute journey with the fundamental Sa Re Ga Ma Pa Dha Ni Sa scale. This lesson builds the tonal foundation every flutist needs to progress confidently.',
    learns: [
      'Correct finger placement for all seven swaras',
      'Steady breath support for each note',
      'Moving smoothly between adjacent notes',
      'Matching pitch with a tanpura drone',
    ],
    previewDuration: '1:25',
    emoji: '🎵',
    bgColor: '#4F7FFA',
  },
  {
    id: 'scale-02',
    title: 'Full Sargam',
    name: 'Complete Octave',
    category: 'Scales',
    difficulty: 'Beginner',
    lessonCount: 5,
    description:
      'Master the full Sa Re Ga Ma Pa Dha Ni Sa in both ascending and descending forms. You will develop consistent tone quality across the entire range of your flute.',
    learns: [
      'Ascending (aaroha) and descending (avaroha) patterns',
      'Breath management across the full octave',
      'Evenness of tone on each swara',
      'Slow to medium tempo practice techniques',
      'Self-monitoring with a tuner',
    ],
    previewDuration: '1:40',
    emoji: '🎶',
    bgColor: '#7C5CBF',
  },
  {
    id: 'scale-03',
    title: 'Upper Octave Scale',
    name: 'Taar Saptak',
    category: 'Scales',
    difficulty: 'Intermediate',
    lessonCount: 6,
    description:
      'Explore the bright upper register of the bansuri by mastering Taar Saptak. Overblowing techniques and refined embouchure control are the key focus areas.',
    learns: [
      'Controlled overblow for taar saptak notes',
      'Embouchure adjustment for higher pitches',
      'Connecting mandra and taar saptaks seamlessly',
      'Breath pressure consistency in the upper register',
      'Avoiding shrillness on high notes',
    ],
    previewDuration: '2:05',
    emoji: '⭐',
    bgColor: '#F97316',
  },
  {
    id: 'scale-04',
    title: 'Komal Swar Scale',
    name: 'Flat Notes Mastery',
    category: 'Scales',
    difficulty: 'Intermediate',
    lessonCount: 5,
    description:
      'Dive into the expressive world of komal (flat) notes — Re, Ga, Dha, and Ni. These notes give Hindustani music its characteristic emotional depth and colour.',
    learns: [
      'Precise half-holing technique for komal Re and Ga',
      'Komal Dha and Ni fingering patterns',
      'Blending komal notes within a phrase',
      'Intonation accuracy for microtonal inflections',
    ],
    previewDuration: '1:55',
    emoji: '🎼',
    bgColor: '#0EA5E9',
  },
  {
    id: 'scale-05',
    title: 'Tivra Ma Scale',
    name: 'Sharp Fourth Note',
    category: 'Scales',
    difficulty: 'Intermediate',
    lessonCount: 4,
    description:
      'Tivra Ma (raised Ma) transforms a scale into a distinctly different musical landscape, as heard in Raga Yaman. Learn precise fingering and intonation for this important note.',
    learns: [
      'Fingering for tivra (sharp) Ma',
      'Contrasting shuddha and tivra Ma in context',
      'Using tivra Ma to build melodic tension',
      'Incorporating tivra Ma into simple phrases',
    ],
    previewDuration: '1:30',
    emoji: '✨',
    bgColor: '#22C55E',
  },
  {
    id: 'scale-06',
    title: 'Raga Yaman Scale',
    name: 'Evening Raga Foundation',
    category: 'Scales',
    difficulty: 'Intermediate',
    lessonCount: 7,
    description:
      'Raga Yaman is the quintessential evening raga built on all seven shuddha notes plus tivra Ma. Study its characteristic aaroha, avaroha, and distinctive vadi-samvadi relationship.',
    learns: [
      'Yaman aaroha with tivra Ma skip',
      'Characteristic phrases (pakad) of Yaman',
      'Vadi (Ga) and samvadi (Ni) emphasis',
      'Slow alap in Yaman',
      'Simple taan patterns in Yaman',
    ],
    previewDuration: '2:30',
    emoji: '🌟',
    bgColor: '#A855F7',
  },
  {
    id: 'scale-07',
    title: 'Raga Bhairavi Scale',
    name: 'Morning Raga Colours',
    category: 'Scales',
    difficulty: 'Intermediate',
    lessonCount: 7,
    description:
      'Bhairavi is a deeply emotive morning raga using all five komal notes. Its poignant character makes it one of the most beloved ragas in classical and semi-classical music.',
    learns: [
      'All-komal scale fingering fluency',
      'Bhairavi pakad and characteristic phrases',
      'Meend between komal notes',
      'Expressing shringar and karuna rasas',
      'Common Bhairavi compositions',
    ],
    previewDuration: '2:20',
    emoji: '🎤',
    bgColor: '#EC4899',
  },
  {
    id: 'scale-08',
    title: 'Raga Kafi Scale',
    name: 'Komal Ga and Ni',
    category: 'Scales',
    difficulty: 'Intermediate',
    lessonCount: 5,
    description:
      'Raga Kafi uses komal Ga and komal Ni, giving it a folk-like, earthy quality perfect for thumri and dadra compositions. Build fluency in its characteristic swings and oscillations.',
    learns: [
      'Kafi scale aaroha and avaroha',
      'Oscillation (andolan) on komal Ga',
      'Kafi pakad phrases',
      'Linking mandra and madhya saptaks in Kafi',
    ],
    previewDuration: '1:50',
    emoji: '🎻',
    bgColor: '#14B8A6',
  },
  {
    id: 'scale-09',
    title: 'Raga Bhimpalasi',
    name: 'Afternoon Raga Depth',
    category: 'Scales',
    difficulty: 'Advanced',
    lessonCount: 8,
    description:
      'Raga Bhimpalasi is a profound afternoon raga with komal Ga and Ni, known for its meditative and serene character. Its intricate phrases reward careful, patient practice.',
    learns: [
      'Bhimpalasi aaroha skipping Re',
      'Characteristic meend from Pa to Ga',
      'Slow alap construction in Bhimpalasi',
      'Bandish in Teentaal',
      'Layakari variations at medium tempo',
    ],
    previewDuration: '3:00',
    emoji: '🔥',
    bgColor: '#EF4444',
  },
  {
    id: 'scale-10',
    title: 'Raga Bhairav',
    name: 'Dawn Raga Grandeur',
    category: 'Scales',
    difficulty: 'Advanced',
    lessonCount: 8,
    description:
      'Raga Bhairav with its komal Re and komal Dha carries an austere, devotional grandeur suited to early morning practice. Learn to render its majestic mood with authority.',
    learns: [
      'Bhairav scale with both komal notes',
      'Gamak ornaments on Re and Dha',
      'Extended alap in Bhairav',
      'Jor and jhala introductory patterns',
      'Traditional composition in Bhairav',
    ],
    previewDuration: '3:15',
    emoji: '🎯',
    bgColor: '#6366F1',
  },
  {
    id: 'scale-11',
    title: 'Double Octave Scale',
    name: 'Mandra to Taar',
    category: 'Scales',
    difficulty: 'Advanced',
    lessonCount: 6,
    description:
      'Traverse two full octaves in a single breath-controlled arc, from mandra (low) to taar (high) saptak and back. This exercise expands your range and breath capacity dramatically.',
    learns: [
      'Seamless register transitions across two octaves',
      'Consistent tone quality from low Sa to high Sa',
      'Breath planning for two-octave phrases',
      'Speed control in ascending and descending runs',
      'Two-octave taan practice',
    ],
    previewDuration: '2:45',
    emoji: '🎸',
    bgColor: '#F59E0B',
  },
  {
    id: 'scale-12',
    title: 'Chromatic Scale',
    name: 'All 12 Semitones',
    category: 'Scales',
    difficulty: 'Advanced',
    lessonCount: 5,
    description:
      'Play all 12 semitones of the chromatic scale on bansuri using half-holing and cross-fingering techniques. This challenges both finger agility and intonation precision.',
    learns: [
      'Half-holing for chromatic notes',
      'Cross-fingering techniques for accidentals',
      'Equal intonation across all 12 pitches',
      'Chromatic exercise patterns for dexterity',
    ],
    previewDuration: '2:10',
    emoji: '🎹',
    bgColor: '#64748B',
  },

  // ─── SONGS ──────────────────────────────────────────────────────────────────
  {
    id: 'song-01',
    title: 'Simple Melody Bansuri Dhun',
    name: 'First Tune',
    category: 'Songs',
    difficulty: 'Beginner',
    lessonCount: 3,
    description:
      'Your very first complete melody on the bansuri, designed to be easy, beautiful, and deeply satisfying. This dhun uses only five notes so you can focus on tone and expression.',
    learns: [
      'Playing a complete melody from start to finish',
      'Note transitions without gaps or squeaks',
      'Dynamic variation within a simple tune',
      'Keeping steady rhythm while playing a melody',
    ],
    previewDuration: '1:15',
    emoji: '🎵',
    bgColor: '#4F7FFA',
  },
  {
    id: 'song-02',
    title: 'Pal Pal Dil Ke Paas',
    name: 'Bollywood Classic',
    category: 'Songs',
    difficulty: 'Beginner',
    lessonCount: 4,
    description:
      'Render this timeless Bollywood melody on flute with warmth and feel. The tune\'s flowing phrases make it ideal for practising legato and smooth note connections.',
    learns: [
      'Legato phrasing on a vocal melody',
      'Matching the melodic curve of the original song',
      'Gentle use of meend between close notes',
      'Breath placement within song phrases',
    ],
    previewDuration: '1:45',
    emoji: '🎶',
    bgColor: '#EC4899',
  },
  {
    id: 'song-03',
    title: 'Raghupati Raghav Raja Ram',
    name: 'Devotional Bhajan',
    category: 'Songs',
    difficulty: 'Beginner',
    lessonCount: 3,
    description:
      'This beloved bhajan is simple, steady, and perfect for building rhythmic confidence. Its repetitive structure helps you focus on tone and breath evenness.',
    learns: [
      'Playing in a steady rhythmic cycle',
      'Simple ornaments on devotional melodies',
      'Building musical stamina through repetition',
      'Expressing devotional mood through tone',
    ],
    previewDuration: '1:20',
    emoji: '✨',
    bgColor: '#F59E0B',
  },
  {
    id: 'song-04',
    title: 'Jana Gana Mana',
    name: 'National Anthem',
    category: 'Songs',
    difficulty: 'Beginner',
    lessonCount: 3,
    description:
      'Learn to play the Indian National Anthem with precision and dignity. This piece covers most of the middle octave and teaches articulation and clear note separation.',
    learns: [
      'Clean note articulation with tongue',
      'Playing in Bb scale (standard bansuri key)',
      'Correct phrasing for anthem-style music',
      'Controlling breath for stately passages',
    ],
    previewDuration: '1:10',
    emoji: '🌟',
    bgColor: '#22C55E',
  },
  {
    id: 'song-05',
    title: 'Vande Mataram',
    name: 'Patriotic Classic',
    category: 'Songs',
    difficulty: 'Intermediate',
    lessonCount: 5,
    description:
      'Vande Mataram carries a majestic, emotionally charged melody that blossoms on the bansuri. This lesson covers the full song with all its dynamic peaks and valleys.',
    learns: [
      'Wide dynamic range from soft to strong',
      'Upper octave passages in taar saptak',
      'Sustaining long notes with vibrato',
      'Building climactic musical phrases',
      'Performance-level stamina across a full song',
    ],
    previewDuration: '2:00',
    emoji: '🎯',
    bgColor: '#F97316',
  },
  {
    id: 'song-06',
    title: 'Man Tarpat Hari Darshan Ko',
    name: 'Classical Devotional',
    category: 'Songs',
    difficulty: 'Intermediate',
    lessonCount: 6,
    description:
      'This gem from Baiju Bawra is set in Raga Malkauns and carries deep spiritual longing. Rendering it on flute requires refined meend, gamak, and tonal control.',
    learns: [
      'Raga Malkauns melodic framework',
      'Expressive meend glides between notes',
      'Gamak ornaments for emotional impact',
      'Slow vilambit rendition of a composition',
      'Bridging classical and devotional styles',
    ],
    previewDuration: '2:35',
    emoji: '🎼',
    bgColor: '#6366F1',
  },
  {
    id: 'song-07',
    title: 'Pahadi Dhun',
    name: 'Mountain Folk Melody',
    category: 'Songs',
    difficulty: 'Intermediate',
    lessonCount: 4,
    description:
      'Pahadi dhuns evoke the vast open landscapes of the Himalayas with their pentatonic simplicity and natural sway. This lesson captures that open-air, folk quality on bansuri.',
    learns: [
      'Pentatonic scale fluency',
      'Natural swaying rhythmic feel',
      'Improvising within a folk melody',
      'Open, resonant tone for outdoor-style playing',
    ],
    previewDuration: '1:50',
    emoji: '🎵',
    bgColor: '#14B8A6',
  },
  {
    id: 'song-08',
    title: 'O Re Piya',
    name: 'Romantic Film Song',
    category: 'Songs',
    difficulty: 'Intermediate',
    lessonCount: 5,
    description:
      'The flute-heavy arrangement of O Re Piya is beloved for its soaring phrases and intimate mood. This lesson teaches you how to play its iconic melody with full expression.',
    learns: [
      'Legato phrasing across register breaks',
      'Controlled vibrato on sustained notes',
      'Dynamic shaping within a phrase',
      'Interpreting a film melody with classical sensibility',
      'Managing long vocal-style phrases',
    ],
    previewDuration: '2:10',
    emoji: '🎤',
    bgColor: '#A855F7',
  },
  {
    id: 'song-09',
    title: 'Sur Na Saje Piya Basanti',
    name: 'Classical Thumri Song',
    category: 'Songs',
    difficulty: 'Intermediate',
    lessonCount: 6,
    description:
      'Piya Basanti is a semi-classical masterpiece blending folk simplicity with classical ornamentation. Playing it on flute develops your expressive vocabulary significantly.',
    learns: [
      'Thumri-style ornaments (murki, khatka)',
      'Playful, light articulation',
      'Call-and-response phrasing',
      'Spontaneous improvisation within a fixed frame',
      'Connecting verses smoothly',
    ],
    previewDuration: '2:25',
    emoji: '🎶',
    bgColor: '#EF4444',
  },
  {
    id: 'song-10',
    title: 'Bhairavi Thumri',
    name: 'Classical Vocal Rendition',
    category: 'Songs',
    difficulty: 'Advanced',
    lessonCount: 8,
    description:
      'Thumri in Bhairavi is the epitome of Hindustani light classical music, rich with sentiment and ornamental freedom. This lesson teaches you to render it with depth and authenticity.',
    learns: [
      'Full Bhairavi raga grammar for thumri',
      'Complex meend chains across multiple notes',
      'Bol-baant improvisation technique',
      'Layering ornaments for emotional impact',
      'Spontaneous bol-alap within thumri form',
    ],
    previewDuration: '3:20',
    emoji: '🔥',
    bgColor: '#EC4899',
  },
  {
    id: 'song-11',
    title: 'Raga Yaman Bandish',
    name: 'Classical Composition',
    category: 'Songs',
    difficulty: 'Advanced',
    lessonCount: 9,
    description:
      'A traditional bandish in Raga Yaman set to Teentaal teaches the formal structure of Hindustani classical composition. You will learn sthayi, antara, and layakari variations.',
    learns: [
      'Sthayi and antara structure',
      'Teentaal tala cycle and sam',
      'Slow vilambit bandish rendering',
      'Drut bandish (fast composition)',
      'Improvised taan passages in Yaman',
    ],
    previewDuration: '3:45',
    emoji: '🎻',
    bgColor: '#7C5CBF',
  },
  {
    id: 'song-12',
    title: 'Raag Bhairav Composition',
    name: 'Dawn Classical Piece',
    category: 'Songs',
    difficulty: 'Advanced',
    lessonCount: 8,
    description:
      'A traditional Bhairav bandish played at dawn captures a mood of solemnity and spiritual awakening. This lesson builds your classical performance foundation.',
    learns: [
      'Bhairav bandish sthayi and antara',
      'Alap preceding the bandish',
      'Characteristic gamak runs in Bhairav',
      'Connecting alap, jor, and bandish',
      'Performance presentation skills',
    ],
    previewDuration: '3:30',
    emoji: '🎯',
    bgColor: '#0EA5E9',
  },

  // ─── EXERCISES ──────────────────────────────────────────────────────────────
  {
    id: 'ex-01',
    title: 'Breath Control Basics',
    name: 'Diaphragmatic Breathing',
    category: 'Exercises',
    difficulty: 'Beginner',
    lessonCount: 4,
    description:
      'Great flute playing starts with great breathing. This lesson trains your diaphragm and teaches the steady, controlled airstream that is the foundation of beautiful tone.',
    learns: [
      'Diaphragmatic breathing technique',
      'Long tone breath support on Sa',
      'Controlled exhale for sustained phrases',
      'Breath intake without tension',
    ],
    previewDuration: '1:10',
    emoji: '💨',
    bgColor: '#22C55E',
  },
  {
    id: 'ex-02',
    title: 'Long Tone Exercise',
    name: 'Tone Development',
    category: 'Exercises',
    difficulty: 'Beginner',
    lessonCount: 4,
    description:
      'Holding each note for four or more beats develops tone richness, embouchure stability, and breath support. This is the single most effective daily practice exercise.',
    learns: [
      'Steady embouchure across a held note',
      'Even airstream for rich tone quality',
      'Crescendo and decrescendo on a single note',
      'Listening critically to your own sound',
    ],
    previewDuration: '1:30',
    emoji: '🎵',
    bgColor: '#4F7FFA',
  },
  {
    id: 'ex-03',
    title: 'Swara Sadhana',
    name: 'Note Meditation',
    category: 'Exercises',
    difficulty: 'Beginner',
    lessonCount: 5,
    description:
      'Swara Sadhana is the daily discipline of playing each note slowly and mindfully against a drone. It refines intonation, tone, and your inner musical ear over time.',
    learns: [
      'Tuning each swara against a tanpura',
      'Identifying and correcting pitch deviations',
      'Developing a strong sruti (intonation) sense',
      'Patient, focused practice mindset',
      'Building consistency across all seven swaras',
    ],
    previewDuration: '1:45',
    emoji: '🎶',
    bgColor: '#14B8A6',
  },
  {
    id: 'ex-04',
    title: 'Alankar Level 1',
    name: 'Basic Ornament Patterns',
    category: 'Exercises',
    difficulty: 'Beginner',
    lessonCount: 5,
    description:
      'Alankars are systematic note-pattern exercises that build finger coordination, evenness, and tonal consistency across the flute\'s range. Level 1 covers basic ascending patterns.',
    learns: [
      'SRGM RGMP GMPD MPDN PDNS pattern',
      'Even spacing between notes at slow tempo',
      'Synchronising fingers and breath',
      'Building muscle memory for scale patterns',
    ],
    previewDuration: '1:35',
    emoji: '🎼',
    bgColor: '#F59E0B',
  },
  {
    id: 'ex-05',
    title: 'Alankar Level 2',
    name: 'Intermediate Patterns',
    category: 'Exercises',
    difficulty: 'Intermediate',
    lessonCount: 6,
    description:
      'Level 2 alankars introduce grouped note patterns, skips, and descending runs to challenge your coordination and mental mapping of the flute\'s layout.',
    learns: [
      'Grouped three-note ascending patterns',
      'Descending (avaroha) alankar sequences',
      'Skipping note patterns for finger agility',
      'Increasing tempo incrementally with metronome',
      'Maintaining tone quality at faster speeds',
    ],
    previewDuration: '2:00',
    emoji: '⭐',
    bgColor: '#6366F1',
  },
  {
    id: 'ex-06',
    title: 'Alankar Level 3',
    name: 'Advanced Patterns',
    category: 'Exercises',
    difficulty: 'Advanced',
    lessonCount: 7,
    description:
      'Level 3 alankars combine complex skips, wide interval jumps, and two-octave patterns that push finger speed and breath control to a new level of excellence.',
    learns: [
      'Two-octave alankar runs',
      'Wide interval (Pa-Sa, Ga-Ni) jump patterns',
      'Triplet and sixteenth-note subdivisions',
      'Coordinating breath across long alankar sequences',
      'Building speed while preserving clarity',
    ],
    previewDuration: '2:20',
    emoji: '🔥',
    bgColor: '#EF4444',
  },
  {
    id: 'ex-07',
    title: 'Tongue Articulation',
    name: 'Ta Ti Te Tu Patterns',
    category: 'Exercises',
    difficulty: 'Beginner',
    lessonCount: 4,
    description:
      'Clean tongue articulation gives your notes a precise, defined attack. This lesson drills Ta, Ti, Te, Tu syllables to develop crisp, consistent articulation across the range.',
    learns: [
      'Single-tongue (Ta) technique',
      'Varied syllable articulation (Ti, Te, Tu)',
      'Staccato passages with tongue',
      'Tonguing at increasing tempos',
    ],
    previewDuration: '1:20',
    emoji: '🎯',
    bgColor: '#F97316',
  },
  {
    id: 'ex-08',
    title: 'Finger Speed Exercise',
    name: 'Dexterity Training',
    category: 'Exercises',
    difficulty: 'Intermediate',
    lessonCount: 5,
    description:
      'Rapid finger movement is essential for taans and fast alankars. This lesson uses targeted drills to build independent finger strength and lightning-fast reflexes.',
    learns: [
      'Isolated finger lift exercises',
      'Adjacent-finger independence drills',
      'Fast chromatic and scalar runs',
      'Using a metronome for gradual speed increase',
      'Relaxed hand posture at high speeds',
    ],
    previewDuration: '1:55',
    emoji: '🎸',
    bgColor: '#A855F7',
  },
  {
    id: 'ex-09',
    title: 'Meend Glide Technique',
    name: 'Slide Between Notes',
    category: 'Exercises',
    difficulty: 'Intermediate',
    lessonCount: 5,
    description:
      'Meend — the continuous glide between two notes — is one of the most expressive tools in Hindustani music. Master slow, controlled glides and increase their speed progressively.',
    learns: [
      'Slow meend from Ma to Ga',
      'Rolling fingertip technique for smooth glide',
      'Controlling pitch during half-hole transitions',
      'Multi-note meend chains',
      'Using meend expressively in a melody',
    ],
    previewDuration: '2:00',
    emoji: '✨',
    bgColor: '#0EA5E9',
  },
  {
    id: 'ex-10',
    title: 'Vibrato Technique',
    name: 'Tone Oscillation',
    category: 'Exercises',
    difficulty: 'Intermediate',
    lessonCount: 5,
    description:
      'A natural, warm vibrato enriches tone and brings your playing to life. This lesson teaches diaphragmatic vibrato and jaw/lip vibrato, and how to blend them musically.',
    learns: [
      'Diaphragmatic pulse for vibrato',
      'Jaw vibrato and its application',
      'Controlling vibrato speed and depth',
      'Adding vibrato to long tones',
      'Selective use of vibrato for expression',
    ],
    previewDuration: '1:55',
    emoji: '🎤',
    bgColor: '#EC4899',
  },
  {
    id: 'ex-11',
    title: 'Gamak Exercise',
    name: 'Heavy Ornamental Strokes',
    category: 'Exercises',
    difficulty: 'Advanced',
    lessonCount: 6,
    description:
      'Gamak is a forceful, oscillating ornament that adds power and intensity to classical flute playing. This exercise builds the breath pressure and finger strength gamak demands.',
    learns: [
      'Forceful breath pulse for gamak',
      'Rapid oscillation between two notes',
      'Gamak patterns on Pa-Ga and Ni-Dha',
      'Maintaining intonation during heavy gamak',
      'Using gamak in raga performance context',
    ],
    previewDuration: '2:30',
    emoji: '🎯',
    bgColor: '#64748B',
  },
  {
    id: 'ex-12',
    title: 'Taan Level 1',
    name: 'Basic Fast Runs',
    category: 'Exercises',
    difficulty: 'Intermediate',
    lessonCount: 6,
    description:
      'Taan is the fast scalar run that showcases speed, clarity, and musical intelligence. Level 1 introduces straight ascending and descending taans at moderate tempo.',
    learns: [
      'Straight taan in one octave',
      'Uniform note duration in fast runs',
      'Landing precisely on sam (beat one)',
      'Building speed with a metronome',
      'Breath management across a full taan',
    ],
    previewDuration: '2:05',
    emoji: '🌟',
    bgColor: '#7C5CBF',
  },
  {
    id: 'ex-13',
    title: 'Taan Level 2',
    name: 'Complex Fast Runs',
    category: 'Exercises',
    difficulty: 'Advanced',
    lessonCount: 7,
    description:
      'Level 2 taans involve two-octave runs, vakra (zigzag) patterns, and mixed-interval shapes that test both speed and musical creativity. Push your boundaries here.',
    learns: [
      'Two-octave ascending and descending taans',
      'Vakra (zigzag) taan patterns',
      'Sapaat taan at high speed',
      'Taan improvisation in a raga context',
      'Cleanly ending taans on the mukhra',
    ],
    previewDuration: '2:45',
    emoji: '🔥',
    bgColor: '#F97316',
  },
  {
    id: 'ex-14',
    title: 'Palte Permutations',
    name: 'Note Permutation Drills',
    category: 'Exercises',
    difficulty: 'Advanced',
    lessonCount: 8,
    description:
      'Palte exercises systematically permute groups of notes through all their combinations, building extraordinary finger independence and note-mapping across the entire flute range.',
    learns: [
      'All permutations of three-note groups',
      'Four-note permutation patterns',
      'Applying palte across two octaves',
      'Speed and evenness in complex patterns',
      'Mental visualisation of note combinations',
    ],
    previewDuration: '3:00',
    emoji: '🎹',
    bgColor: '#22C55E',
  },
];
